version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lerehausseur
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

###< doctrine/doctrine-bundle ###
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
