version: '3'

services:
###> doctrine/doctrine-bundle ###
  database_test:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    container_name: lerehausseur-test
    environment:
      POSTGRES_DB: lerehausseur-test
      # You should definitely change the password in production
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5435:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
